#!/bin/bash

cd ~
git clone https://github.com/AllenInstitute/neuroanalysis
cd neuroanalysis
python setup.py develop

cd ~
git clone https://github.com/AllenInstitute/aisynphys
cd aisynphys
git fetch origin
python setup.py develop

exec "$@"
