#!/bin/bash

cd ~
git clone https://github.com/AllenInstitute/neuroanalysis
cd neuroanalysis
python setup.py develop

cd ~
git clone https://github.com/AllenInstitute/multipatch_analysis
cd multipatch_analysis
git checkout notebooks
python setup.py develop


exec "$@"
